### ISSUE TITLE
Optimise the evaluation pipeline (concept_calculation)

### ISSUE THREAD

**Issue by Karthi-DStech** [Health-Informatics-UoN/lettuce#33]

**Comment by kuraisle** [comment]
Can you describe this for me please?

**Comment by Karthi-DStech** [comment]
Yeah sure, James. I've finished the entire part of the evaluation and when I was performing the final test, I noticed there was some space to optimise it. I found that some of the informal names use LLM twice to get the formal name. 

So before clearing it now itself, I thought of pushing the code for review and later we can optimise it by making some changes in API calls. I am currently commenting on the code and soon I'll push it for a PR. I hope once you run the code, you can spot the issue.

**Comment by kuraisle** [comment]
@Karthi-DStech do we still need this issue?
